// <auto-generated />
namespace MvcProjectWeek.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddPhoto : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddPhoto));
        
        string IMigrationMetadata.Id
        {
            get { return "201604190022442_AddPhoto"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
